### PR TITLE
add -main to the list of things to ignore

### PR DESCRIPTION
**Pull request by AndreaCrotti**
Still untested, and have to write a test for it (I wanted to add a WIP label but I can't)
BTW @borkdude in my fork https://github.com/AndreaCrotti/carve/pull/1
I enabled circleci so we can see the test results directly, would be nice to do it here as well.

### CODE REVIEW

**Comment by borkdude** [comment]
You can set your PR as Draft so it's not mergable. 
This project already uses .circleci: https://github.com/borkdude/carve/tree/master/.circleci so I'm not sure what you mean?

**Comment by borkdude** [comment]
See: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by AndreaCrotti** [comment]
Ah ok I mean it's not reporting in the PR the status of the build
Screenshot 2020-02-04 at 14 03 19

And ok cool I didn't know about draft PRs, I'll have a look

**Comment by borkdude** [comment]
@AndreaCrotti Feel free to fix the .circleci config. I'm not sure what should change there?

**Pull request closed without merging**
